# Self-Hosted Github Action Runners on Azure via https://cirun.io
# Reference:
# - https://docs.cirun.io/reference/yaml#azure
# - https://docs.cirun.io/cloud/azure
# - https://docs.cirun.io/custom-images/cloud-custom-images#azure-custom-images
# - https://github.com/thebrowsercompany/infra/tree/main/azure
runners:
  # X64 machines.
  - name: cirun-win11pro-23h2-x64-8
    cloud: azure
    instance_type: Standard_B8als_v2
    machine_image:
      #id: "/subscriptions/fe7bef8e-1cf6-4ac1-9385-be50a1504961/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-x64/versions/2024.02.22"
      publisher: MicrosoftWindowsDesktop
      offer: windows-11
      sku: win11-23h2-pro
      version: 22631.2861.231204
    labels:
      - cirun-win11-x64-8
  - name: cirun-win11pro-23h2-x64-64
    cloud: azure
    instance_type: Standard_F64s_v2
    machine_image:
      #id: "/subscriptions/fe7bef8e-1cf6-4ac1-9385-be50a1504961/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-x64/versions/2024.02.22"
      publisher: MicrosoftWindowsDesktop
      offer: windows-11
      sku: win11-23h2-pro
      version: 22631.2861.231204
    labels:
      - cirun-win11-x64-64

# Enable once cirun supports arm64.
#  # ARM64 machines.
#  - name: cirun-win11pro-23h2-arm64-8
#    cloud: azure
#    instance_type: Standard_D8pls_v5
#    machine_image:
#      id: "/subscriptions/fe7bef8e-1cf6-4ac1-9385-be50a1504961/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-arm64/versions/2024.02.23"
#    labels:
#      - cirun-win11-arm64-64
#  - name: cirun-win11pro-23h2-arm64-64
#    cloud: azure
#    instance_type: Standard_D64pls_v5
#    machine_image:
#      id: "/subscriptions/fe7bef8e-1cf6-4ac1-9385-be50a1504961/resourceGroups/Win-CI/providers/Microsoft.Compute/galleries/base_images/images/win11-23h2-pro-arm64/versions/2024.02.23"
#    labels:
#      - cirun-win11-arm64-64
